let objLista = {
    um: 0,
    dois: 0,
    tres: 0,
    quatro: 0,
    cinco: 0,
    seis: 0,
    sete: 0,
    oito: 0,
    nove: 0,
    dez: 0,
    onze: 0,
    doze: 0,
    treze: 0,
    quatorze: 0,
    quinze: 0,
    dezesseis: 0,
    dezessete: 0,
    dezoito: 0,
    dezenove: 0,
    vinte: 0,
    vinte_um: 0,
    vinte_dois: 0,
    vinte_tres: 0,
    vinte_quatro: 0,
    vinte_cinco: 0,
    vinte_seis: 0,
    vinte_sete: 0,
    vinte_oito: 0,
    vinte_nove: 0,
    trinta: 0,
    trinta_um: 0,
    trinta_dois: 0,
    trinta_tres: 0,
    trinta_quatro: 0,
    trinta_cinco: 0,
    trinta_seis: 0,
    trinta_sete: 0,
    trinta_oito: 0,
    trinta_nove: 0,
    quarenta:0,
    quarenta_um: 0,
    quarenta_dois: 0,
    quarenta_tres: 0,
    quarenta_quatro: 0,
    quarenta_cinco: 0,
    quarenta_seis: 0,
    quarenta_sete: 0,
    quarenta_oito: 0,
    quarenta_nove: 0,
    cinquenta:0,
    cinquenta_um: 0,
    cinquenta_dois: 0,
    cinquenta_tres: 0,
    cinquenta_quatro: 0,
    cinquenta_cinco: 0,
    cinquenta_seis: 0,
    cinquenta_sete: 0,
    cinquenta_oito: 0,
    cinquenta_nove: 0,
    sessenta:0
}

module.exports = objLista